### ISSUE TITLE
Load balancer deletion through vpc-cleanup fails & blocking

### ISSUE THREAD

**Issue by VidyasagarMSC** [IBM-Cloud/vpc-tutorials#27]
<img width="1440" alt="Screenshot 2019-03-28 at 8 33 24 PM" src="https://user-images.githubusercontent.com/6552440/55168523-fe030380-5198-11e9-8a51-483220085f48.png">
<img width="1440" alt="Screenshot 2019-03-28 at 8 34 00 PM" src="https://user-images.githubusercontent.com/6552440/55168525-fe030380-5198-11e9-8331-6d783bf18055.png">

**Comment by data-henrik** [comment]
Still an issue (maybe caused by timeout) or can this be closed?

**Comment by VidyasagarMSC** [comment]
This is a temporary fix due to changing states of load balancer from DELETE --> UPDATE_PENDING-->ACTIVE-->DELETE
