### ISSUE TITLE
Support REUSE_VPC and PREFIX to cleanup only a subset of the resources

### ISSUE THREAD

**Issue by l2fprod** [IBM-Cloud/vpc-tutorials#31]
When I reuse a VPC between tests, I'd like to cleanup the VPC of all resources matching a basename+prefix, no matter which script created them

Two usecases:
1/ delete all resources and keep the VPC
2/ delete all resources matching basename+prefix and keep the VPC

https://github.com/IBM-Cloud/vpc-tutorials/blob/d2f61fe5fd324c4054b25ec59dfeef5082870a95/scripts/vpc-cleanup.sh#L13

**Comment by data-henrik** [comment]
addressed by https://github.com/IBM-Cloud/vpc-tutorials/commit/8681ff4d723dc33fd93e8961522238c83580cb94

**Comment by data-henrik** [comment]
```
$ ./scripts/vpc-cleanup.sh 
usage: ./scripts/vpc-cleanup.sh vpc-name [--keep true] [--prefix pattern] [-f, --force]
Removes a VPC and its related resources
  --keep true         Keep the VPC and only delete resources within
  --prefix pattern    Only delete resources with names starting with specified pattern
  --force, -f         Force the operation without confirmation
```
