### ISSUE TITLE
If the instance fails to create the next call to jq fails silently

### ISSUE THREAD

**Issue by l2fprod** [IBM-Cloud/vpc-tutorials#33]
Everytime we use `$(...)` if something goes wrong inside the parenthesis, the error is silently ignored and the rest of the script may not work properly

https://github.com/IBM-Cloud/vpc-tutorials/blob/d2f61fe5fd324c4054b25ec59dfeef5082870a95/scripts/bastion-create.sh#L103

I had this run:
```
Reusing VPC automated-tests-do-not-delete
5d61fb04-97bd-46a0-8f78-fdab9688f581
Bastion: no image specified, using Ubuntu
Bastion: no bastion name specified, using 'bastion'
... waiting for automated-tests-fredl--bastion-subnet of subnets to be available
.subnets now available
Bastion: Creating rules
Bastion: Creating bastion VSI
parse error: Invalid numeric literal at line 2, column 0
... waiting for automated-tests-fredl--bastion-vsi of instances to be running
.........................................................................................................................................................................................................................................................................................................................................................
```

the bastion VSI failed to created - I don't know why but the instance was marked "failed". Likely the call to `instance-create --json` did not return a valid JSON document and thus the call to `jq` fails, from there the all script is broken

**Comment by VidyasagarMSC** [comment]
This happens with subnets as well

**Comment by l2fprod** [comment]
any use of "$(...)"

**Comment by l2fprod** [comment]
```
set -e
set -o pipefail
```

can help to fail when using `|` in commands

**Comment by l2fprod** [comment]
looking at this we should avoid all calls like "ibmcloud .... | jq" and instead:

- run "ibmcloud" command and capture its output
- test ibmcloud return code
- if the command failed, display the output (so we can debug) and exit the script
- else continue with the script

**Comment by data-henrik** [comment]
The above changes will also make the scripts more readable and the individual parts easier to reuse.

**Comment by data-henrik** [comment]
see https://github.com/IBM-Cloud/vpc-tutorials/commit/e8ebbb5ffc72eb328b76e20a78b4f9a678442bb5 for erroring out
need to print output of ibmcloud (assigned to variable) on error

**Comment by l2fprod** [comment]
less frequent error as we use more terraform
