### ISSUE TITLE
build.sh - poll instead of waiting for 120 seconds

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/vpc-tutorials#44]
During a build.sh:
```
2019-05-30 14:25:05 ./build.sh: Pending for 120 seconds before running application init.
```

Is it possible to poll?  120 is likely too long.  But it might not be long enough.

**Comment by dprosper** [comment]
The issue here is the server is `active`, but not yet accepting ssh commands. When it fails to accept ssh commands I am not seeing an error.   Not completely sure yet how to poll/validate it is ready... maybe loop through an `ls` command until something is returned...

**Comment by powellquiring** [comment]
I've tried this before:
```
retry_until_true(lambda: shell_it('ssh -F {} root@{} uname -a'.format(SSH_TMP_INSECURE_CONFIG, ip), truefalse=True))
```
ls should work as well as uname

**Comment by dprosper** [comment]
This is fixed in the upcoming release. Closing it now to clean up task list ...
