### ISSUE TITLE
build.sh virtual_server_instance element has unused type key

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/vpc-tutorials#48]
The virtual_server_instances in the cockroach example has the key "type".  I do not believe this is used.  If the idea that it useful to add arbitrary key/value to the introduced types that would be ok if some docs are provided on why that is useful and an example for how it is used.

Instead I spent time searching through the code looking for usages.

vpc-tutorials/vpc-cockroachdb-mzr/vpc-cockroachdb-mzr.template.json:

```
      "virtual_server_instances": [
        {
          "name": "vsi",
          "type": "cockroachdb",
...
```

Expected: no type key or docs that explain why this is useful.

**Comment by dprosper** [comment]
it is not used in the main scripts, but it is used in the custom scripts for the cockroach scenario, here: https://github.com/IBM-Cloud/vpc-tutorials/blob/3f8d598c61836685bc66c5d59f6d3e13e4f775cc/vpc-cockroachdb-mzr/ssh-init/cockroachdb.sh#L23.  We can add more details in the docs when this is fully baked.
