### ISSUE TITLE
build.sh virtual_server_instances cloud_init and ssh_init should be filenames 

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/vpc-tutorials#49]
The virtual_server_instance cloud_init and ssh_init should be path names relative to the configuration template file that names them.

My use case is to demonstrate provisioning of software using terraform, ansible and the cli.  The build.sh script is being used to demonstrate the cli.  I would like to share the cloud-init script in the directory that is a parent to to the terraform/ ansible/ and cli/ examples.  The build.sh template might look like this:

```
      "virtual_server_instances": [
        {
          "name": "vsi",
          "cloud_init": "../cloud-config.yaml",
          "ssh_init": "../initialize.sh"
...
        }
      ]
```

Expected: the above would work.

Actual, the files must be in cloud_init/cloud-config.yaml and ssh_init/initialize.sh

```
      "virtual_server_instances": [
        {
          "name": "vsi",
          "cloud_init": "cloud-config.yaml",
          "ssh_init": "initialize.sh"
...
        }
      ]
```

**Comment by l2fprod** [comment]
no longer exist
