### ISSUE TITLE
build.sh virtual_server_instances ssh_init should be post_provision and documented

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/vpc-tutorials#50]
In this example ssh_init is used to execute post provision scripts that happen to have ssh related stuff in them.  I got faked out thinking it was going to execute the ssh_scripts on the vsi itself.  Changing the name to something like post_provision, post_provision_script, post_install or something would help self document.

```
      "virtual_server_instances": [
        {
...
          "floating_ip": {
            "name": "fip-1"
          },
          "cloud_init": "cloud-config.yaml",
          "ssh_init": "bootstrapmin.sh"
        }
```

The execution context of this script is going to need to be documented as well.  The current implementation sources the script and the examples in cockroach use the functions and variables provided as well as parse the state file.

This makes all of this stuff part of the API.  Consider passing parameters that will be the API and let the user do more stuff at the peril of future incompatibility.

**Comment by powellquiring** [comment]
floating ip need to flow to these scripts.  Currently something like this is used:

```
#!/bin/bash
set -x
log_info "${BASH_SOURCE[0]}: Running SSH script $vsi_ssh_init on $vsi_name using IP address $vsi_ipv4_address."
script=bootstrapmin.sh
floating_ip=$(jq -r '.vpc[].virtual_server_instances[]? | select(.name == "vsi") | .floating_ip.address' ${configFile})
```

Note the use of the VSI name to find the floating ip.  This way to connect is fragile since changing the name of a vsi will result in an unexpected side effect, namely this script will stop working.

**Comment by powellquiring** [comment]
As you can see from above I was debugging this script and added a `set -x`.
- Script is sourced and had the side effect of setting -x for all subsequent execution
- I wanted to use `set -e` but this is likely to have undesired side effects due to the script being sourced

**Comment by l2fprod** [comment]
no longer exist
