### ISSUE TITLE
if the delete script fails during the vpc-cockroachdb-mzr test , it will leak Key Protect and Certificate Manager instances

### ISSUE THREAD

**Issue by l2fprod** [IBM-Cloud/vpc-tutorials#57]
if the delete script fails or can not be run, some of the resources it creates will not be deleted:

![image](https://user-images.githubusercontent.com/12746550/60437639-1b6bc180-9c0f-11e9-8b78-5e8a571ac559.png)

**Comment by l2fprod** [comment]
given we create all resources in the "automated-tests" group, once _simple_ procedure is to extend the tests/teardown.sh with instructions to delete all services found in the resource group as part of the global generic cleanup

**Comment by dprosper** [comment]
Interesting, have you noted the errors during a failed delete (I guess I can look at the CI logs)

**Comment by l2fprod** [comment]
most likely it happens when the job times out (50min for a Travis job)

**Comment by l2fprod** [comment]
https://github.com/IBM-Cloud/vpc-tutorials/commit/6a1cd865134d2c03fe7bed9182e904a887785bef
